// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testgrpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string clientName = 1;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();
}
